- hosts: localhost
  tasks:
    - name: Test that my module works
      kazoo_accounts:
          base_url: 
          auth_pass:
          auth_user:
          auth_realm: 
          account_name: 
          account_realm:
          state: enabled


      register: result

    - debug: var=result